<a href="https://colab.research.google.com/github/labviros/computer-vision-topics/blob/version2020/lesson01-basics/basic_math_for_cv_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Mathematics for Computer Vision with Python - Part 1 - Vectors
Computer vision tools and techniques are highly dependent on linear algebraic operations.
In this notebook we will cover some linear algebraic operation and properties of vectors that are required for our course on Computer Vision(CV).



---


##Libraries required
The main library used here is [Numpy](http://www.numpy.org/), wich is part of [Scipy](https://www.scipy.org/) "Python-based ecosystem of open-source software for mathematics, science, and engineering".

To begin with the codes, we use this common import:

In [1]:
import numpy as np
import scipy



## Vector Declaration
In a 2D cartesian plane, vectors and points are represented the same way.
> $p=(x,y)$ \\
> $w=(u,v)$

In this case, the magnitude of $w$ is denoted as $\left \| w \right \|$ and is given by the following:
>  $\left \| w \right \|=\sqrt{u^{2}+v^{2}}$.

In Python, a vector can be represented by a one-dimensional list, as show below:

In [2]:
p = [3,4,8.7,3,10,9]
v = [1,50,0,7,8]
print(p)
print(v)

[3, 4, 8.7, 3, 10, 9]
[1, 50, 0, 7, 8]


One common property required may be the length of the vector, which is given as follows:

In [3]:
length = len(p)
print("The length of p is ",length)
length = len(v)
print("The length of v is ",length)


The length of p is  6
The length of v is  5


Actually, in order to use the numpy library you have to declare a numpy array object, with a python array as input argument, as folows:

In [4]:
v1 = np.array(v)
print(v1)
p = np.array([1,2,3,4,5,6,7.3, 8, 9])
print(p)

[ 1 50  0  7  8]
[1.  2.  3.  4.  5.  6.  7.3 8.  9. ]


Some information about vectors or matrices that may be needed are: data type, array size and data content. You can get such information by using the following methods:

In [ ]:
print('Data type:', v1.dtype)
print('Vector size:',v1.size)
print('Data: ', v1)

print('Data type:', p.dtype)
print('Vector size:',p.size)
print('Data: ', p)

Data type: int64
Vector size: 5
Data:  [ 1 50  0  7  8]
Data type: float64
Vector size: 9
Data:  [1.  2.  3.  4.  5.  6.  7.3 8.  9. ]


**Attention:**
In Python the first index of a vector is 0 (zero).


To select one element or part of the vector, you can do as follows:

In [ ]:
print('Vector p: ', p,'\n')
print('Fourth element: ',p[3],'\n')
print('From the first to the fifth element: ', p[0:5],'\n')
print('Last element: ',p[-1],'\n')
print('Subvector1: ', p[2:-1],'\n')
print('Subvector2: ', p[1:4],'\n')
print('Subvector3: ', p[3:6], '\n' )
print(p)
print(p[:])
print(p[3:])
print(p[:4])
print(p[0:6:2])

Vector p:  [1.  2.  3.  4.  5.  6.  7.3 8.  9. ] 

Fourth element:  4.0 

From the first to the fifth element:  [1. 2. 3. 4. 5.] 

Last element:  9.0 

Subvector1:  [3.  4.  5.  6.  7.3 8. ] 

Subvector2:  [2. 3. 4.] 

Subvector3:  [4. 5. 6.] 

[1.  2.  3.  4.  5.  6.  7.3 8.  9. ]
[1.  2.  3.  4.  5.  6.  7.3 8.  9. ]
[4.  5.  6.  7.3 8.  9. ]
[1. 2. 3. 4.]
[1. 3. 5.]
[9.  8.  7.3 6.  5.  4.  3.  2.  1. ]


## Vectors operations and properties
Some common operatios and properties of vectors are as follows:

* Addition
* Subtraction
* Vector multiplication
* Vector norm
* Ortogonality

### Addition
Let's say there are two vectos denoted as follows:

In [8]:
v1 = np.array([2,0,4,7])
v2 = np.array([4,5.4,6,5])

The resulting element-wise sum is calculed this way:

In [9]:
v12 = v1 + v2
print(v12)
v21 = v2 + v1
print(v21)


[ 6.   5.4 10.  12. ]
[ 6.   5.4 10.  12. ]


### Subtraction
Subtraction is similar to adittion; and instead of the element-wise sum, we compute the element-wise difference:

In [10]:
v12 = v1-v2
print(v12)

[-2.  -5.4 -2.   2. ]


### Vector multiplication
There are two methods of computing vector multiplication:
* Dot product
* Cross product

#### Dot product
Is the sum of the element-wise products of two vectors:
> $dot\left ( V_1 , V_2 \right )= V_1 . V_2 = {\sum_{i}{v_{1}^{i} .  v_{2}^{i}}}$

Where $v_{1}^{i}$ and $v_{2}^{i}$  are the elements of vectors $V_{1}$ and $V_{2}$ respectively

Another notation that is commonly used is:
> ${V_1}^T V_2 = V_1 . V_2$


In Python, we can compute this using Numpy:

In [12]:
v1 = np.array([2,0,3])
v2 = np.array([4,5,6])
print(np.dot(v1,v2))
print(v1@v2)

26
26


#### Cross product
This takes two vectors and computes a new vector that is orthogonal to both original ones  
> $V_3 = V_1 \times V_2$

The resulting vetor is:

> $V_3 = \begin{bmatrix}
v_{1y}v_{2z} - v_{1z}v_{2y}\\
v_{1z}v_{2x} - v_{1x}v_{2z}\\
v_{1x}v_{2y} - v_{1y}v_{2x} \\
\end{bmatrix}$

The cross product can also is represented as:

>$V_3 = \hat{V_1}V_2$

where $\hat{V_1}$ is the skew-symmetric matrix of $V_1$.

> $V_3 = \begin{bmatrix}
0 & -v_{1z} &  v_{1y} \\
v_{1z} &0 &  -v_{1x} \\
-v_{1y} & v_{1x} &  0  
\end{bmatrix}\begin{bmatrix}
v_{2x} \\
v_{2y} \\
v_{2z}
\end{bmatrix} = \begin{bmatrix}
v_{1y}v_{2z} - v_{1z}v_{2y}\\
v_{1z}v_{2x} - v_{1x}v_{2z}\\
v_{1x}v_{2y} - v_{1y}v_{2x} \\
\end{bmatrix}$


In Python we can compute the cross product as folows:

In [13]:
v1 = np.array([2,0,4])
v2 = np.array([4,5,6])
print(np.cross(v1,v2))
print(np.cross(v2,v1))

[-20   4  10]
[ 20  -4 -10]


### Vector norm
A $L_{pth}$ norm of a vector $V$ is given as follows

> $\left \| V  \right \|_p = \left ( \sum_{i}^{n}\left | v_i \right |^p \right ) ^\frac{1}{p}$



The two most popular norms for vectors are the L1 and L2 norms:


*  $L_1$ norm is given as:
>  $\left \| V  \right \|_1 =  \sum_{i}^{}\left | v_i \right | $

and a example is shown here:



In [14]:
v = np.array([2,-6,4,5])
print(np.linalg.norm(v,ord=1))

17.0


* The $L_2$ norm is given as:
>  $\left \| V  \right \|_2 =  \left (\sum_{i}^{}\left | v_i \right |² \right ) ^\frac{1}{2} = \sqrt{\sum_{i}^{}\left | v_i \right |²} $

and a example is as folows:



In [15]:
v = np.array([2,3,4,5])
print(np.linalg.norm(v,ord=2))

7.3484692283495345


### Orthogonality
Two vectors are said to be orthogonal if their dot product is zero. From grometric point of view, if the two vectors are perpendicular, they are said to be orthogonal to each other:

In [17]:
v1=np.array([2,3,4])
v2=np.array([6,1,-3]) # orthogonal to v1
print(np.dot(v1,v2))

3


In [18]:
v1 = np.array([2,0,4])
v2 = np.array([4,5,6])
v3 = np.cross(v1,v2)
print(v3)
print(np.dot(v1,v3))
print(np.dot(v3,v2))


[-20   4  10]
0
0
